![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np
my_array=np.array(range(10))
print(my_array)
print(my_array[::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [2]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [3]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [4]:
array_1 = np.arange(1, 21)
array_2 = np.reshape(array_1, (4, 5))
print(array_2)

array_3=np.transpose(array_2)
print(array_3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [5]:
array_2[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [22]:
print(array_2[::2, ::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [7]:
print(array_2[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [23]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
#Método 1
lista=[]
for animal in x:
    if animal=="Loro":
        lista.append(animal)
print(np.array(lista))

loros=x[x=="Loro"]
print(loros)

['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [9]:
array_8=np.arange(20)
array_8.reshape([2,5,2])

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [10]:
print(array_2)
print(array_2[-1::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [29]:
array_9=np.zeros(10, dtype=np.uint8)
array_9[3]=1
print("Espacio que ocupa:",array_9.nbytes)
print(array_9)

Espacio que ocupa: 10
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [30]:
array_10=np.arange(10,50)
print(array_10)

print(array_10[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [32]:
array_11=np.array([1,2,0,0,4,0])
a=np.array((np.where(array_11 !=0)))
print(a)

[[0 1 4]]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [14]:
array_12=np.random.rand(100)
print(np.reshape(array_12,[10,10]))

print("Mínimo:",min(array_12))
print("Máximo:",max(array_12))

[[0.30316035 0.64170269 0.76040678 0.21379251 0.05243231 0.99128067
  0.78501315 0.72578778 0.73268402 0.84914223]
 [0.55156833 0.96193799 0.12213975 0.98477139 0.59821296 0.07675365
  0.21168486 0.25652383 0.61398387 0.11415185]
 [0.75329125 0.51648983 0.63361542 0.16074353 0.02193719 0.79644432
  0.50574239 0.49370918 0.82094149 0.58527651]
 [0.77029607 0.52284422 0.02172788 0.48600695 0.7473847  0.34901071
  0.65728563 0.54149271 0.32715728 0.35314699]
 [0.7223184  0.51870607 0.90478407 0.06615378 0.29111225 0.70981372
  0.85119797 0.67460504 0.21738089 0.16175505]
 [0.26585681 0.73620518 0.49163059 0.71949595 0.35711874 0.02488084
  0.49913902 0.90758405 0.91304958 0.3506354 ]
 [0.06943848 0.86019171 0.62846543 0.44994346 0.07095827 0.37249608
  0.28562693 0.55698179 0.91073758 0.30363282]
 [0.02427099 0.49685368 0.13845794 0.68689475 0.02671496 0.58881379
  0.34996252 0.11654077 0.10634301 0.88220779]
 [0.92264469 0.67633866 0.00885097 0.7159099  0.93477319 0.55893175
  0.05496272

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [15]:
array_13=np.random.rand(30)
print("Media:",(sum(array_13)/len(array_13)))

Media: 0.4487655855464098


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [16]:
import numpy as np

num=6

if num<2:
    print("Introduzca un número >1 para que sea un array 2D")
else:
    data=num*"0"+(num-2)*("0"+(num-2)*"1"+"0")+num*"0"
    array_2D=np.array(list(data))
    print(array_2D.reshape([num,num]))

[['0' '0' '0' '0' '0' '0']
 ['0' '1' '1' '1' '1' '0']
 ['0' '1' '1' '1' '1' '0']
 ['0' '1' '1' '1' '1' '0']
 ['0' '1' '1' '1' '1' '0']
 ['0' '0' '0' '0' '0' '0']]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [17]:
list1=[0,1,0,1,0,1,0,1]
list2=[1,0,1,0,1,0,1,0]

list_final=(list1+list2)*4
matriz_8x8=np.array(list_final)
matriz_8x8.reshape(8,8)


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [35]:
arr=np.zeros((8,8))
arr[::2, 1::2]=1
arr[1::2, ::2]=1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [18]:
list=[0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0]
np.tile(list,4).reshape(8,8)


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [36]:
matriz1=np.random.rand(25)
matriz2=(matriz1-np.mean(matriz1))/np.std(matriz1)

print("Matriz random 5x5: \n",matriz1)
print("Matriz normalizada: \n",matriz2)

Matriz random 5x5: 
 [0.46030712 0.52013567 0.32613952 0.18805806 0.3068722  0.11652879
 0.30652874 0.86935053 0.30606463 0.25297161 0.70093757 0.48735735
 0.80919896 0.27724413 0.50056634 0.31919833 0.36855415 0.42070508
 0.6692735  0.7784695  0.35823927 0.69690078 0.03872386 0.52461911
 0.69589688]
Matriz normalizada: 
 [ 0.03832865  0.31284369 -0.57728078 -1.21084848 -0.66568623 -1.53905064
 -0.66726216  1.91516774 -0.66939166 -0.91300162  1.14242821  0.1624449
  1.63917057 -0.80163054  0.22305251 -0.60912947 -0.38266715 -0.14337983
  0.99714197  1.4981727  -0.42999553  1.12390592 -1.89604776  0.33341532
  1.11929967]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [38]:
secuencia=np.arange(11)
print(secuencia)

for i in secuencia:
    if (i >2 and i <9):
        secuencia[i]=-1
print(secuencia)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [84]:
tablero=np.full(fill_value=" ", shape=(10,10))
tablero[:2,1]="O"
tablero[1,3:7]="O"
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [11]:
x_shoot, y_shoot=(1, 3)
tablero[x_shoot, y_shoot]="X"
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'X', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [12]:
x_shoot, y_shoot=(5, 5)
tablero[x_shoot, y_shoot]="-"
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'X', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', '-', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [99]:
orient="W"

x_orig, y_orig=(3,1)
boat_size=4

if orient=="N":
    tablero[x_orig:(x_orig-boat_size):-1,y_orig]="O"
    


if orient=="S":
    tablero[x_orig:(x_orig+boat_size),y_orig]="O"


if orient=="E":
    tablero[x_orig,y_orig:(y_orig+boat_size)]="O"

if orient=="W":
    tablero[x_orig,y_orig:(y_orig-boat_size+1):-1]="O"

print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' 'O' 'O' 'O' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [21]:
import random
#Definimos las variables:
tamano_tablero=(10,10)
barco1=2
barco2=4

tablero= np.full(shape=(tamano_tablero),fill_value=("()"))
print(tablero)

#Generamos la posición de los barcos aleatoiamente
tablero_cambios=tablero.copy()

barco_posicionado=0

while barco_posicionado<2:
    #Generamos posición y random
    fila=random.randint(1,10)
    print(fila)
    columna=random.randint(1,10)
    print(columna)
    ejes = (1, 2, 3, 4)
    eje_int = random.randrange(len(ejes))
    eje_dict = {1: 'N', 2: 'S', 3: 'E', 4: 'O'}
    eje = eje_dict[eje_int+1]
    print(eje)

    
    break

[['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']
 ['()' '()' '()' '()' '()' '()' '()' '()' '()' '()']]
8
5
O
