![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
import numpy as np
my_array=np.array(range(10))
print(my_array)
print(my_array[::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [4]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [5]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [6]:
array_1 = np.arange(1, 21)
array_2 = np.reshape(array_1, (4, 5))
print(array_2)

array_3=np.transpose(array_2)
print(array_3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [7]:
array_2[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [8]:
array_1 = np.arange(1, 21)
array_2 = np.reshape(array_1, (4, 5))

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [36]:
# new_array=(array_2[0:3])
# new_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [44]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
lista=[]
for animal in x:
    if animal=="Loro":
        lista.append(animal)
print(np.array(lista))


['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [10]:
array_8=np.arange(20)
array_8.reshape([2,5,2])

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [69]:
print(array_2)
print(array_2[-1::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[1 2 3 4 5]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [11]:
array_9=np.zeros(10)
array_9[3]=1
print(array_9.nbytes)
print(array_9)


80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [12]:
array_10=np.arange(10,50)
print(array_10)

print(array_10[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [13]:
array_11=np.array([1,2,0,0,4,0])

a=np.array((np.where(array_11 !=0)))
print(a)

[[0 1 4]]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [14]:
array_12=np.random.rand(100)
print(np.reshape(array_12,[10,10]))

print("Mínimo:",min(array_12))
print("Máximo:",max(array_12))

[[0.19255409 0.08594084 0.239398   0.34766996 0.74166067 0.57054759
  0.41032875 0.24314861 0.97671658 0.73172221]
 [0.11112659 0.2533859  0.06833391 0.1101965  0.24109306 0.17258148
  0.73902332 0.37216186 0.68015514 0.66897897]
 [0.25536042 0.282514   0.39369321 0.24007313 0.68826779 0.08570767
  0.44390478 0.48172666 0.75827725 0.03250772]
 [0.64595202 0.86909953 0.74436929 0.30301181 0.43667951 0.47068933
  0.98239568 0.17396965 0.6813975  0.00820903]
 [0.60234974 0.38312994 0.69579084 0.45205592 0.7285002  0.34033177
  0.54293623 0.16281703 0.86527718 0.21204466]
 [0.70434442 0.14344965 0.4685315  0.81822606 0.30821604 0.35177945
  0.77014633 0.82943572 0.42636076 0.87668944]
 [0.98659917 0.86531768 0.77268984 0.50462949 0.88718019 0.25821076
  0.66986    0.66630013 0.1449699  0.76419381]
 [0.5795047  0.61963095 0.48628419 0.43292327 0.1719791  0.70510397
  0.49626361 0.81998713 0.866878   0.99601014]
 [0.77595994 0.20111229 0.14240704 0.0426274  0.65235772 0.03012133
  0.92197303

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [15]:
array_13=np.random.rand(30)
print("Media:",(sum(array_13)/len(array_13)))

Media: 0.45489269442141267


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [71]:
import numpy as np
num=9
data=num*"0"+(num-2)*("0"+(num-2)*"1"+"0")+num*"0"
array_2D=np.array(list(data))
print(array_2D.reshape([num,num]))



[['0' '0' '0' '0' '0' '0' '0' '0' '0']
 ['0' '1' '1' '1' '1' '1' '1' '1' '0']
 ['0' '1' '1' '1' '1' '1' '1' '1' '0']
 ['0' '1' '1' '1' '1' '1' '1' '1' '0']
 ['0' '1' '1' '1' '1' '1' '1' '1' '0']
 ['0' '1' '1' '1' '1' '1' '1' '1' '0']
 ['0' '1' '1' '1' '1' '1' '1' '1' '0']
 ['0' '1' '1' '1' '1' '1' '1' '1' '0']
 ['0' '0' '0' '0' '0' '0' '0' '0' '0']]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [79]:
list1=[0,1,0,1,0,1,0,1]
list2=[1,0,1,0,1,0,1,0]

matriz_8x8=np.array()
matriz_8x8.reshape(8,8)

TypeError: array() missing required argument 'object' (pos 0)

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [17]:
tablero= np.full(shape=(10,10),fill_value=('O'))
print(tablero)

[['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
 ['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']]
